name: Waka Readme

on:
  schedule:
    - cron: "30 18 * * *"   # 00:00 IST (18:30)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN:         ${{ secrets.GH_TOKEN }}  # PAT classic (repo + read:user)

          SECTION_NAME: "waka"
                                          # <!--START_SECTION:waka--> ... <!--END_SECTION:waka-->
          LOCALE: "en"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_SHORT_INFO: "true"         # üì¶, üèÜ, üö´, üìú, üîë
          SHOW_COMMIT: "false"
          SHOW_DAYS_OF_WEEK: "true"       # ‚ÄûI'm Most Productive on ‚Ä¶‚Äú
          SHOW_UPDATED_DATE: "false"
          SHOW_TIMEZONE: "true"
          SHOW_LANGUAGE: "true"
          SHOW_EDITORS: "false"
          SHOW_PROJECTS: "true"
          SHOW_OS: "true"
          SHOW_LOC_CHART: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_LANGUAGE_PER_REPO: "true"
